apiVersion: v1
kind: Service
metadata:
  name: mariadb-connector-service
spec:
  selector:
    app: mariadb-connector
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
  type: ClusterIP
