apiVersion: v1
kind: Service
metadata:
  name: mongodb-connector-service
spec:
  selector:
    app: mongodb-connector
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
  type: ClusterIP
